version: '3.9'

services:

  apache-php:
    build: .
    container_name: 'calisthenics-lab'
    ports:
      - '8084:80'
    volumes:
      - ./:/var/www
    environment:
      PHP_EXTENSION_PDOSQLITE: 1
      PHP_EXTENSION_PDO_SQLITE: 1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
