version: '3.9'

services:

  apache-php:
    build: .
    container_name: 'integration-tests-lab'
    ports:
      - '8085:80'
    volumes:
      - ./:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
